version: "3.8"
services:
  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timesheet-db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  timesheet-app:
    image: amani12th/achatimg:2.0.0
    depends_on:
      - mysql-db
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysql-db:3306/timesheet-db?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username": "root",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    ports:
      - "8082:8082"
volumes:
  db-data: